version: '3.6'

services:
   db:
     image: mysql:8
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_DATABASE: mydb
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpass
     ports:
       - "127.0.0.1:3306:3306"
     container_name: mysqldb
