version: '3.6'

services:
   db:
     image: neo4j:3.4
     restart: always
     environment:
         NEO4J_AUTH: none
     ports:
       - "127.0.0.1:7474:7474"
       - "127.0.0.1:7687:7687"
     container_name: neodev
